name: CI
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Neovim nightly
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: nightly

      - name: Install Lua
        uses: leafo/gh-actions-lua@v13
        with:
          luaVersion: "luajit"

      - name: Install Luarocks
        uses: leafo/gh-actions-luarocks@v6

      - name: Install Luacheck
        run: luarocks install luacheck

      - name: Install lua-language-server
        run: |
          LUALS_VERSION=3.18.2
          LUALS_RELEASE_URL=https://github.com/LuaLS/lua-language-server/releases/download/${LUALS_VERSION}/lua-language-server-${LUALS_VERSION}-linux-x64.tar.gz
          LUALS_INSTALL_PATH=$HOME/.local/lua-language-server

          curl -L -o lua-language-server.tar.gz $LUALS_RELEASE_URL
          mkdir -p $LUALS_INSTALL_PATH
          tar -xzf lua-language-server.tar.gz -C $LUALS_INSTALL_PATH
          echo "$LUALS_INSTALL_PATH/bin" >> $GITHUB_PATH

      - name: Verify dependencies
        run: |
          nvim --version
          luacheck --version
          lua-language-server --version

      - name: Lint
        run: make lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Neovim nightly
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: nightly

      - name: Verify Installation
        run: nvim --version

      - name: Test
        run: make test

  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: JohnnyMorganz/stylua-action@v5.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: 2.5.2
          args: lua --check
